#!/bin/sh

MSP430_MCU="msp430fr2433"

echo $(pwd)

cmake \
    -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DCMAKE_SYSTEM_NAME="elf" \
    -DCMAKE_SYSTEM_PROCESSOR="msp430" \
    -DCMAKE_C_COMPILER_TARGET="msp430-elf" \
    -DCMAKE_CXX_COMPILER_TARGET="msp430-elf" "$@"
#    -DCMAKE_CXX_FLAGS="-mmcu=${MSP430_MCU}" \
#    -DCMAKE_C_FLAGS="-mmcu=${MSP430_MCU}" \
#    "$@"

#    -DCMAKE_CXX_COMPILER="msp430-elf-g++" \
#    -DCMAKE_C_COMPILER="msp430-elf-gcc" \
